### ISSUE TITLE
Baza użytkowników

### ISSUE THREAD

**Issue by nabanaa** [nabanaa/work_scheduler#3]
utworzyć baze danych użytkowników kompatybilną z flaskiem. Dobrze żeby przechowywała tez dyspozycyjności na najbliższy miesiąc

**Comment by rafalBaron** [comment]
Podstawowa baza jest zrobiona (w sumie to tylko dyspozycyjności tabela na ten moment jest używana), ale trzeba uzgodnić architekturę aby robić dokładniejsze rzeczy. Póki co można dodać dyspozycyjnośc do bazy i usunąć.
